### ISSUE TITLE
mypy reports error with target unpacking

### ISSUE THREAD

**Issue by bandophahita** [ScreenPyHQ/screenpy_selenium#2]
Consider this valid code:

```python
target = Target.("thing").located_by((By.ID, "thingid"))
def do_thing(by, value):
    ...

do_thing(*target)  # mypy errors  'List or tuple expected as variable arguments'
```

`Target` allows for unpacking to occur but mypy will error: "List or tuple expected as variable arguments".  Based on a [stackoverflow post](https://stackoverflow.com/a/68687978/2532408) it would seem that mypy is expecting the object to also have an `__iter__` method. 

Now, I'm not sure if we actually need `Target` to have an `__iter__` or if we could get away with type hinting that one exists.

```python
class Target:
    __iter__: Callable[["Target"], Iterator[Any]]
```

**Comment by perrygoy** [comment]
Nice find! This would be nice to fix.

**Comment by MarcelWilson** [comment]
While the type hint alleviates mypy I'm thinking it might just be a better idea to implement the method.  The question I have now is; does it make sense to keep both `__iter__` and `__getitem__`?  does it even matter?  From what I can tell `__getitem__` is a legacy method but they essentially accomplish the same thing.

Point of fact, I'm having a REALLY difficult time trying to figure out a unit test that passes _only_ when `__iter__` exists.
