### ISSUE TITLE
Take screenshot example AttachmentTypes is not clear where is applicable

### ISSUE THREAD

**Issue by Scot3004** [ScreenPyHQ/screenpy_selenium#23]
# Steps to reproduce

Given a user opens [the documentation of screenpy_selenium](https://screenpy-selenium-docs.readthedocs.io/en/latest/extended_api/actions.html#savescreenshot)

When the user tries to replicate the example
```python
the_actor.attempts_to(
    SaveScreenshot.as_(filepath).and_attach_it_with(
        attachment_type=AttachmentTypes.PNG,
    ),
)
```

# Expected result
The snippet works as expected

# Actual Result
The test fails because AttachmentTypes.PNG does not exists

After opening the example [screenpy_selenium/github](https://github.com/ScreenPyHQ/screenpy_examples/tree/trunk/screenpy_selenium/github) I realized that the expected import is:
```python
from allure_commons.types import AttachmentType
```

But is not clear in the given example that this only works if I'm using the `screenpy_adapter_allure` package

**Comment by perrygoy** [comment]
Oh! Thank you for this—this example is actually from before the extensions were split out. I'll move this example to ScreenPy Adapter: Allure's documentation!

**Comment by perrygoy** [comment]
The docs have been updated! Sorry for the two-month-long turnaround!
