### ISSUE TITLE
Cannot install the lastest version of selenium (4.8.0)

### ISSUE THREAD

**Issue by Scot3004** [ScreenPyHQ/screenpy_selenium#24]
When I try to install the lastest version of selenium I get the following error

ERROR: Cannot install screenpy-selenium==4.0.3 and selenium==4.8.0 because these package versions have conflicting dependencies.

```bash
The conflict is caused by:
    The user requested selenium==4.8.0
    screenpy-selenium 4.0.3 depends on selenium<4.5 and >=4.1.0
```

I want to upgrade selenium because I'm getting the following warnings

```bash
==================================================== warnings summary ====================================================
tests/test_home.py: 6 warnings
tests/features/test_homepage.py: 7 warnings
  /home/scot3004/proyectos/comunidades/django-quilla-web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py:387: DeprecationWarning: HTTPResponse.getheader() is deprecated and will be removed in urllib3 v2.1.0. Instead use HTTPResponse.headers.get(name, default).
    if response.getheader('Content-Type'):

tests/test_home.py: 6 warnings
tests/features/test_homepage.py: 7 warnings
  /home/scot3004/proyectos/comunidades/django-quilla-web/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py:388: DeprecationWarning: HTTPResponse.getheader() is deprecated and will be removed in urllib3 v2.1.0. Instead use HTTPResponse.headers.get(name, default).
    content_type = response.getheader('Content-Type').split(';')

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================ 2 passed, 26 warnings in 12.73s =============================================
```

It seems to be fixed in selenium 4.6.1 https://github.com/SeleniumHQ/selenium/issues/11313

**Comment by perrygoy** [comment]
No, this is our problem. We haven't released the new version for ScreenPy Selenium yet that uncaps the upper bounding for Selenium.

If you look in our `pyproject.toml`, this issue is actually fixed: https://github.com/ScreenPyHQ/screenpy_selenium/blob/trunk/pyproject.toml#L51

This was another one we were waiting on fully releasing until after ScreenPy's next release, but... let's just release a minor now and another minor later. :P

I'll take a look and see if we can release tonight. Thanks for the issue!

**Comment by perrygoy** [comment]
@Scot3004 sorry for forgetting to reply here, is your issue fixed now?

**Comment by Scot3004** [comment]
I'll check what is the latest version and retry

**Comment by Scot3004** [comment]
Working as expected, tested with selenium 4.11.2
