### ISSUE TITLE
target name isolation

### ISSUE THREAD

**Issue by MarcelWilson** [ScreenPyHQ/screenpy_selenium#39]
After the inclusion of [represent_prop](https://github.com/ScreenPyHQ/screenpy/blob/dea061c3c0e73d7ffbb438fc6353cdee7059b30f/screenpy/speech_tools.py#L64) -- which wraps objects in `< object >`  when logging -- I'm starting to wonder if `Target` name logging should have a similar feature.  

Most of the time language context allows the reader to differentiate what part of the log string is the target vs the beat message, however occasionally a target name can arise that makes reading the log a little more difficult.

Consider the following targets vs logging examples:

```python
EVENTUALLY = Target("eventually").located((By.ID, "eventually"))
actor.will(Eventually(Click(EVENTUALLY)))
```
```
Marcel tries to click on the eventually, eventually.
    Marcel clicks on the eventually.

```
----

```python
NONE = Target("none").located((By.ID, "none"))
actor.will(See(NONE, IsVisible()))
```
```
Marcel sees if the none is visible.
```

---
This is a variation that isn't obvious.  Anyone reading the log would be forgiven if they mistakenly assumed the question was a target.  It isn't.
```python
actor.will(See(TheSideNavExpanded(), IsEqualTo(True)))
```
```
Marcel sees if the side nav expanded is equal to <True>.
```
---
My thought is to make these targets a bit more identifiable by wrapping their names.
```
Marcel sees if the [none] is visible.
Marcel sees if the <none> is visible.
Marcel sees if the `none` is visible.
Marcel sees if the {none} is visible.
```

**Comment by MarcelWilson** [comment]
My first thought was, should screenpy_selenium handle this?  

- It's simple enough for users to add their own text to the target names, should they wish it.
- It's possible not everyone would appreciate seeing their targets wrapped in some extra characters, for some reason.  
- If users that already add their own "flair" around targets would need to adjust.  

All of the above would suggest this feature should be optional somehow.  Which would mean either making the calls to `Target` contain an attribute that needs to be changed for anyone who wants the opposite of the default, or the addition of a global setting.  Possibly both.

My second thought was `screenpy_playwright` and `screenpy_appium` both have a `target` also.  I see no reason why they shouldn't get similar treatment. 

It also occurred to me that `StdOutAdapterSettings` exists in `screenpy` but I'm having a hard time justifying adding a new setting to the `screenpy` package that the sub-packages would be dependent on in order to use.   My gut tells me `StdOutAdapterSettings` would be the most appropriate place for the settings unless there were some way for the sub-packages to enhance the settings.  Thus keeping "SOLID" principles intact.

**Comment by MarcelWilson** [comment]
In my own project I found myself using the ID as the `Target` name in most cases. This tends to work because our ids tend to read well enough.  It also makes spotting the targets _super_ easy because they have dashes between words.  

`Marcel clicks on the close-add-person-success-toast.`

As I read through the regression logs, my brain instantly recognizes dashed text as a target name. 

That said, not all projects have the benefit of always having ids (including mine).  I got around this by naming the targets what I would expect the id to be.

```python
TOP_NAV_HELP = Target("top-nav-help").located((By.XPATH, "//button[@aria-label='help button']"))
```

Again, this works for the majority of cases, but not all.

**Comment by perrygoy** [comment]
I'm in the camp that folks can make this happen if they want it to in their own way. I don't think making `Target` handle it would be maintainable or preferable for most users.

I personally do not wrap my Target names and prefer my logs to read as close to English as i can make them, but i've seen your logs and also like the way those look. I don't think we should prescribe one way or the other.

I was willing to make an exception for `represent_prop` because `hamcrest` already does that for us and because showing somehow that something is a Python native object is also important for debugging.

**Comment by bandophahita** [comment]
Sounds good.  I thought about this over the weekend.  It's pretty simple to Subclass Target if they want.
